import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { createHash } from 'node:crypto';
import { startPreview } from '../src/preview-server.js';
import { patchBundle } from '../src/injector.js';

const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const directory = await fs.mkdtemp(path.join(os.tmpdir(), 'idleon-ui-preview-'));
const output = path.resolve(process.env.IDLEON_PREVIEW_OUTPUT || '../output/playwright');
await fs.mkdir(output, { recursive: true });
const preview = await startPreview({ dataDirectory: directory });
let browser;
let page;
const failures = [];
const wait = (page, predicate) => page.waitForFunction(predicate);
try {
  browser = await chromium.launch({ headless: true, ...(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE ? { executablePath: process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE } : {}) });
  page = await browser.newPage({ viewport: { width: 1440, height: 1040 }, deviceScaleFactor: 1 });
  page.on('pageerror', error => failures.push(error.message));
  const fixture = 'var sampleGameRoot = {}; sampleGameRoot.ApplicationMain = function() {};';
  await page.addInitScript({ content: patchBundle(fixture, createHash('sha256').update(fixture).digest('hex')) + '\nwindow.__gameKeyEvents=[];for(const type of ["keydown","keyup"])window.addEventListener(type,e=>window.__gameKeyEvents.push(type+":"+e.key),true);' });
  await page.goto(preview.url);
  await page.locator('[data-action=name]').waitFor({ state: 'visible' });
  await page.keyboard.down('ArrowRight');
  await page.locator('[data-action=name]').dblclick();
  await page.keyboard.up('ArrowRight');
  await page.locator('.icp-edit').fill('Bossing'); await page.locator('.icp-edit').press('Enter');
  await wait(page, () => document.querySelector('[data-action=name]').getAttribute('aria-label').startsWith('Bossing.'));
  assert.deepEqual(await page.evaluate(() => window.__gameKeyEvents), ['keydown:ArrowRight', 'keyup:ArrowRight']);
  assert.equal(await page.locator('[data-action=name] canvas').count(), 1, 'native bitmap font must render in this installed-font fixture');
  await page.screenshot({ path: path.join(output, 'idleon-card-profiles-desktop.png'), fullPage: true });
  await page.locator('[data-action=name]').dblclick(); await page.locator('.icp-edit').fill('Cancelled'); await page.locator('.icp-edit').press('Escape');
  assert.ok((await page.locator('[data-action=name]').getAttribute('aria-label')).startsWith('Bossing.'));
  await page.locator('[data-action=name]').dblclick(); await page.locator('.icp-edit').fill('Must cancel on switch');
  await page.getByRole('button', { name: 'Select preset 2', exact: true }).click();
  await wait(page, () => document.querySelector('[data-action=name]').getAttribute('aria-label').startsWith('Preset 2.'));
  await page.getByRole('button', { name: 'Select preset 1', exact: true }).click();
  await wait(page, () => document.querySelector('[data-action=name]').getAttribute('aria-label').startsWith('Bossing.'));
  await page.locator('[data-action=name]').dblclick(); await page.locator('.icp-edit').fill('Must cancel on menu');
  await page.locator('#menu').uncheck(); await page.locator('[data-action=name]').waitFor({ state: 'hidden' });
  await page.locator('#menu').check();
  await wait(page, () => document.querySelector('[data-action=name]').getAttribute('aria-label').startsWith('Bossing.'));
  await page.getByRole('button', { name: 'Select preset 2', exact: true }).click();
  await page.locator('[data-action=name]').dblclick(); await page.locator('.icp-edit').fill('Mining');
  await page.locator('footer').click();
  await wait(page, () => document.querySelector('[data-action=name]').getAttribute('aria-label').startsWith('Mining.'));
  await page.getByRole('button', { name: 'Select preset 1', exact: true }).click();
  await page.getByRole('button', { name: 'Save card profile', exact: true }).click();
  await page.getByLabel('Group name', { exact: true }).fill('General setup');
  await page.getByRole('button', { name: 'Save group', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await page.getByRole('button', { name: 'Save card profile', exact: true }).click();
  await page.getByLabel('Save as', { exact: true }).selectOption({ label: 'Update: General setup' });
  await page.getByLabel('Group name', { exact: true }).fill('General setup updated');
  await page.getByRole('button', { name: 'Update group', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await page.locator('[data-action=name]').dblclick(); await page.locator('.icp-edit').fill('Must cancel on character');
  await page.locator('#character').selectOption('Mage');
  await wait(page, () => document.querySelector('[data-action=name]').getAttribute('aria-label').startsWith('Preset 1.'));
  assert.match(await page.locator('#equipped-state').textContent(), /Frog/);
  await page.getByRole('button', { name: 'Load card profile', exact: true }).click();
  await page.screenshot({ path: path.join(output, 'idleon-card-profiles-library.png'), fullPage: true });
  assert.equal(await page.getByRole('button', { name: 'Load', exact: true }).isDisabled(), true);
  assert.equal(await page.locator('.icp-details').count(), 0);
  assert.equal(await page.getByRole('button', { name: /Import|Export/ }).count(), 0);
  await page.getByRole('button', { name: 'Expand General setup updated', exact: true }).click();
  await page.locator('.icp-details').waitFor();
  assert.equal(await page.getByRole('button', { name: 'Load', exact: true }).isDisabled(), true);
  await page.getByRole('button', { name: 'Collapse General setup updated', exact: true }).click();
  await page.getByRole('button', { name: 'About card groups', exact: true }).click();
  await page.getByRole('heading', { name: 'ABOUT CARD GROUPS' }).waitFor();
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: 'General setup updated', exact: true }).click();
  await page.getByRole('button', { name: 'Load General setup updated', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await wait(page, () => document.querySelector('[data-action=name]').getAttribute('aria-label').startsWith('Bossing.'));
  assert.match(await page.locator('#equipped-state').textContent(), /Green Mushroom/);
  await page.getByRole('button', { name: 'Select preset 2', exact: true }).click();
  await wait(page, () => document.querySelector('[data-action=name]').getAttribute('aria-label').startsWith('Mining.'));
  await page.getByRole('button', { name: 'Select preset 1', exact: true }).click();
  await page.getByRole('button', { name: 'Load card profile', exact: true }).click();
  await page.getByRole('button', { name: 'Restore', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await wait(page, () => document.querySelector('[data-action=name]').getAttribute('aria-label').startsWith('Preset 1.'));
  assert.match(await page.locator('#equipped-state').textContent(), /Frog/);
  await page.getByRole('button', { name: 'Load card profile', exact: true }).click();
  const database = JSON.parse(await fs.readFile(path.join(directory, 'profiles.json'), 'utf8'));
  const profiles = Object.values(database.accounts)[0].profiles;
  assert.equal(profiles.length, 1);
  assert.equal(profiles[0].title, 'General setup updated');
  assert.equal(profiles[0].presets[0].cards[0], 'mushroom');
  assert.equal(profiles[0].presets[1].name, 'Mining');
  assert.equal(await page.locator('.icp-details').count(), 0);
  await page.getByRole('button', { name: 'General setup updated', exact: true }).click();
  await page.getByRole('button', { name: 'About card groups', exact: true }).focus();
  await page.keyboard.press('Shift+Tab');
  assert.equal(await page.getByRole('button', { name: 'Load General setup updated', exact: true }).evaluate(node => node === document.activeElement), true);
  await page.getByRole('button', { name: 'Delete General setup updated', exact: true }).click();
  await page.getByRole('heading', { name: 'DELETE GROUP?' }).waitFor();
  await page.getByRole('button', { name: 'Cancel', exact: true }).click();
  assert.equal(await page.locator('.icp-profile').count(), 1);
  await page.getByRole('button', { name: 'Delete General setup updated', exact: true }).click();
  await page.getByRole('button', { name: 'Delete', exact: true }).click();
  await page.getByText('No saved groups yet.', { exact: true }).waitFor();
  assert.equal(await page.getByRole('button', { name: 'Load', exact: true }).isDisabled(), true);
  assert.equal(await page.getByRole('button', { name: 'Restore', exact: true }).isEnabled(), true);
  assert.match(await page.locator('#equipped-state').textContent(), /Frog/);

  await page.getByRole('button', { name: 'Close', exact: true }).click();
  await page.locator('#menu').uncheck(); await page.locator('[data-action=name]').waitFor({ state: 'hidden' });
  await page.locator('#menu').check(); await page.locator('[data-action=name]').waitFor({ state: 'visible' });
  await page.setViewportSize({ width: 1000, height: 760 });
  await page.locator('[data-action=name]').dblclick(); await page.locator('.icp-edit').fill('Mining and chopping setup 1234567'); await page.locator('.icp-edit').press('Enter');
  await wait(page, () => document.querySelector('.icp-edit').hidden);
  await page.screenshot({ path: path.join(output, 'idleon-card-profiles-scaled.png'), fullPage: true });
  await page.reload(); await page.locator('[data-action=name]').waitFor({ state: 'visible' });
  await wait(page, () => document.querySelector('[data-action=name]').getAttribute('aria-label').startsWith('Bossing.'));
  assert.deepEqual(failures, []);
  console.log(JSON.stringify({ passed: true, checks: ['native font', 'double-click rename', 'Enter/Escape/blur', 'keyboard isolation and held key release', 'slot and character isolation', 'cancel on native preset/menu change', 'save whole profile', 'explicit profile update', 'load complete profile', 'unswitched cards captured', 'recovery', 'collapsed group details', 'dynamic Load group name', 'on-demand help', 'delete cancel and confirmation', 'modal keyboard focus', 'menu visibility', 'scaling', 'persistence across reload'], screenshots: output }, null, 2));
} catch (error) {
  if (page) {
    await page.screenshot({ path: path.join(output, 'idleon-preview-failure.png'), fullPage: true });
    console.error(await page.locator('#idleon-card-profiles').innerText());
  }
  throw error;
} finally {
  await browser?.close(); await preview.close(); await fs.rm(directory, { recursive: true, force: true });
}
